# This is a template file for Namadillo config.
# Rename this file to namadillo.config.toml (removing the initial dot) in order to copy it into the Docker container
indexer_url = "https://indexer.namada.tududes.com"
rpc_url = "https://rpc.namada.tududes.com"
masp_indexer_url = "https://masp.namada.tududes.com"