# Uncomment the following lines to define your default indexer and rpc urls
indexer_url = "https://namada-idx.emberstake.xyz"
rpc_url = "https://namada-rpc.emberstake.xyz"
masp_indexer_url = "https://namada-masp-idx.emberstake.xyz"
#localnet_enabled = false
#fathom_site_id = ""
