# Uncomment the following lines to define your default indexer and rpc urls
indexer_url = "https://namada-mainnet-indexer.itrocket.net"
rpc_url = "https://namada-mainnet-rpc.itrocket.net"
masp_indexer_url = "https://namada-mainnet-masp.itrocket.net"
localnet_enabled = false
